### ISSUE TITLE
Office Online Server Always Showing “Unhealthy” Status

### ISSUE THREAD

**Issue by doushichao** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#26]
Office Online Server Always Showing “Unhealthy” Status

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eb30d62f-9a48-d8c2-a755-161611c2399f
* Version Independent ID: c7f7e286-1d24-6e60-91e2-503cd53b8c36
* Content: [部署 Office Online Server](https://docs.microsoft.com/zh-cn/OfficeOnlineServer/deploy-office-online-server)
* Content Source: [OfficeOnlineServer/deploy-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/deploy-office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@doushichao Thank you for this feedback

I want to make sure your server issue is properly addressed. I want to get you over to Support since they have more resources to dig in and see what is going on with your server and will be able to handle this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by doushichao** [comment]
![image](https://user-images.githubusercontent.com/3366393/48455565-a752e980-e7f6-11e8-82ba-475fa3288e5c.png)

**Comment by NoralK** [comment]
I have opened tickets with Microsoft on this very issue and from my experience, with each released *new* GA version, it take a few CU to get the HealthStatus working again.

Support emphasizes that this issue _does not reduce functionality_.  What is failing is one or more of the watchdog services failed.

**Comment by lorenahuangliu** [comment]
Hi -- thank you for your issue submission. We are currently tracking and investigating this issue. I'll update once we have a resolution. Thanks.

**Comment by lorenahuangliu** [comment]
This issue was addressed in the May 2019 PU
