### ISSUE TITLE
OOS to WOPI-Host connections through Forward proxy

### ISSUE THREAD

**Issue by YvesCieters** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#28]
We're hosting an OOS 2016 on Windows Server 2016 that needs to connect to a WOPI-host that's hosted in another datacenter. The OOS to WOPI-host connections should use a forward proxy which is available in the OOS network.
When we try to access the WOPI-host from a browser with the correct proxy server configured we get successful responses.
When we initiate a request for an office online document via the WOPI Frame, we see (using netmon) that the OOS server is trying to access the WOPI-host directly (without proxy).
How can we force OOS to use a proxy server for external connections to the WOPI-Host?

**Comment by AndreaBarr** [comment]
@YvesCieters Thank you for this inquiry

Is there an article you are working off of for the settings? I want to get you to the correct people to assist in this issue. If you are not working off an article my best suggestion would be to go to Support since they will have the resources needed to find a solution for this issue. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
