### ISSUE TITLE
Error since update

### ISSUE THREAD

**Issue by andrekat** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#30]
I've recently updated OOS to the lates version (November 2018). Somehow, I am getting weird exceptions like: "`Microsoft.Office.ServiceInfrastructure.Runtime.Settings.SettingNotDefinedException: Cluster specific setting 'RuntimeGlobalListRefreshInterval' not defined or of the wrong type`" in my ULS.

There is also a new parameter added to the url called "<actnavid=ACTIVITY_NAVIGATION_ID&>" which is not documented yet.

**Comment by AndreaBarr** [comment]
@andrekat Thank you for this feedback

I want to make sure this potential bug gets the appropriate attention. Let's get this over to Support since they will have the resources to take this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by catmanjan** [comment]
I am receiving the same error, I suspect it is due to the fact that I was upgrading.

Rather than trying to resolve the error properly I am just going to blow away the machine and build a new one and see what happens. Will report back.

**Comment by catmanjan** [comment]
Installing on a fresh VM worked for me, probably some junk data left behind from old version
