### ISSUE TITLE
Installing on other than System drive may lead to 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by brettc66** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#34]
The documentation "recommends" installing on system drive but doesn't explicitly state that other installations will fail.
Running the "Add-WindowsFeature NET-Framework-45-Core, NET-Framework-45-ASPNET, Web-Asp-Net45"  command will not resolve the issue.  
To resolve the issue, uninstall OOS, and Language Packs, and re-install on system drive.
Link to article: https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server#deploy-the-office-online-server-farm

**Comment by JasonH-Msft** [comment]
We were generic with the "recommended" term because we can't realistically confirm all the various failure conditions on non-system drives, but also can't state with certainty that installing on non-system drives = automatic failure.  It's recommended because it's the most stable install method with the highest chance of success.
