### ISSUE TITLE
Windows Server 2012 R2- .NET 4.5 error

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#36]
I have created a new VM in Azure and followed these steps.

However, when installing OWA 2013 with SP1, I receive this error:
Setup is unable to proceed due to the following error(s):
This product requires Microsoft .NET Framework 4.5. 
Correct the issue(s) listed above and re-run setup.

The only way appears to be to remove .NET 4.5, but that removes the GUI of Windows. Then you do some hokey install stuff and re-enable the GUI. Is this the only way? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9b2a5b-0d14-1684-ece7-0e50b23316ad
* Version Independent ID: d8b1599c-6164-b7a9-983a-f281f3df86a7
* Content: [Deploy Office Web Apps Server](https://docs.microsoft.com/en-us/webappsserver/deploy-office-web-apps-server)
* Content Source: [OfficeWebAppsServer/deploy-office-web-apps-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeWebAppsServer/deploy-office-web-apps-server.md)
* Product: **office-web-app-server**
* GitHub Login: @mikeplum
* Microsoft Alias: **mikeplum**

**Comment by eschrader** [comment]
I skipped OWA and with OOS for my Azure Win2kR2 VM. Got the ISO from https://my.visualstudio.com/downloads?wt.mc_id=o~msft~devcom~resources

**Comment by JasonH-Msft** [comment]
Unfortunately OOS/OWA isn't supported in Azure VMs, for more details:
https://support.office.com/en-us/article/office-web-apps-and-office-online-server-supportability-in-azure-and-other-iaas-providers-61eb97b6-f83e-4852-bfe8-727b52d884dd 

So for testing, Azure VMs would be ok but technically not supported.

Otherwise possibilities are .NET Framework 4.6 updates can trip up the install, for example:
For .NET Framework 4.6.1 KB: KB3102467
For .NET Framework 4.6  KB: KB3045563
